# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'module3.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from user_payment import Ui_user_payment
from donepage import Ui_donepage
import sqlite3
from un import user
from status import Ui_status



class Ui_module3(object):
    def OK(self):
                self.wc=QtWidgets.QMainWindow()
                self.ui=Ui_user_payment()
                self.ui.setupUi(self.wc)
                self.wc.show()
    
    def QC(self):
                self.wc=QtWidgets.QMainWindow()
                self.ui=Ui_donepage()
                self.ui.setupUi(self.wc)
                self.wc.show()
    def cal(self):
            try:
                pant=int(self.spinBox.text())*10
                shirt=int(self.spinBox_2.text())*8
                kurti=int(self.spinBox_3.text())*20
                punjabi=int(self.spinBox_4.text())*20
                tot=pant+shirt+kurti+punjabi
                self.plainTextEdit_10.setPlainText(str(pant))
                self.plainTextEdit_11.setPlainText(str(shirt))
                self.plainTextEdit_9.setPlainText(str(kurti))
                self.plainTextEdit_12.setPlainText(str(punjabi))
                self.plainTextEdit_13.setPlainText(str(tot))
                connection=sqlite3.connect("MyLaundry.db")
                res= connection.execute("SELECT * FROM user")
                ces=list(res)
                print(ces)
                user=(list(ces[0])[0])
                passw=(list(ces[0])[1])
                conn=None
                c=None
                conn= sqlite3.connect("MyLaundry.db")
                #u=self.plainTextEdit_8.setPlainText()
                r= conn.execute("SELECT Address FROM Registration WHERE Username = ? AND Password=?",(user,passw))
                add=((list(r)[0])[0])
                #r=list(r)
                #print(r[0])
                self.plainTextEdit_8.setPlainText(add)
                c=conn.execute("SELECT * FROM Registration")
                c=list(c)[1]
                print("fin",list(c)[1],type(list(c)[1]))
                res.fetchall()

                c= conn.cursor()
                data = [(user,passw,int(pant),int(shirt),int(kurti),int(punjabi),int(tot))]
                c.executemany("INSERT INTO Request  VALUES(?,?,?,?,?,?,?)",data)
                conn.commit()
                conn.close()
            
            except:
                print("Failed")
        

    def openWindow(self):
                self.wc=QtWidgets.QMainWindow()
                self.ui=Ui_status()
                self.ui.setupUi(self.wc)
                self.wc.show()
 
        
    def setupUi(self, module3):
        module3.setObjectName("module3")
        module3.resize(1337, 918)
        self.centralwidget = QtWidgets.QWidget(module3)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 390, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 470, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 530, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 590, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 640, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(400, 400, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(700, 400, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.m_bt = QtWidgets.QPushButton(self.centralwidget)
        self.m_bt.setGeometry(QtCore.QRect(450, 790, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.m_bt.setFont(font)
        self.m_bt.setObjectName("m_bt")

        self.m_bt.clicked.connect(self.OK)
        
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(140, 710, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_8.setGeometry(QtCore.QRect(360, 700, 341, 61))
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(400, 470, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(400, 530, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(400, 590, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(400, 650, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(-10, 0, 1351, 381))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("l22.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(0, 350, 1361, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.qc_bt = QtWidgets.QPushButton(self.centralwidget)
        self.qc_bt.setGeometry(QtCore.QRect(850, 820, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.qc_bt.setFont(font)
        self.qc_bt.setObjectName("qc_bt")
        self.qc_bt.clicked.connect(self.QC)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(950, 400, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.plainTextEdit_9 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_9.setGeometry(QtCore.QRect(940, 580, 151, 41))
        self.plainTextEdit_9.setObjectName("plainTextEdit_9")
        self.plainTextEdit_10 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_10.setGeometry(QtCore.QRect(940, 460, 151, 41))
        self.plainTextEdit_10.setObjectName("plainTextEdit_10")
        self.plainTextEdit_11 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_11.setGeometry(QtCore.QRect(940, 520, 151, 41))
        self.plainTextEdit_11.setObjectName("plainTextEdit_11")
        self.plainTextEdit_12 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_12.setGeometry(QtCore.QRect(940, 650, 151, 41))
        self.plainTextEdit_12.setObjectName("plainTextEdit_12")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(864, 720, 160, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.plainTextEdit_13 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_13.setGeometry(QtCore.QRect(940, 720, 151, 41))
        self.plainTextEdit_13.setObjectName("plainTextEdit_13")
        self.Calculate = QtWidgets.QPushButton(self.centralwidget)
        self.Calculate.setGeometry(QtCore.QRect(770, 720, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Calculate.setFont(font)
        self.Calculate.setObjectName("Calculate")
        self.Calculate.clicked.connect(self.cal)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(710, 460, 101, 31))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(710, 520, 101, 31))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setGeometry(QtCore.QRect(710, 580, 101, 31))
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_4.setGeometry(QtCore.QRect(710, 650, 101, 31))
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(1140, 410, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(1139, 470, 121, 41))
        self.dateEdit.setObjectName("dateEdit")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(1130, 540, 201, 31))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.pastrecords = QtWidgets.QPushButton(self.centralwidget)
        self.pastrecords.setGeometry(QtCore.QRect(30, 810, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pastrecords.setFont(font)
        self.pastrecords.setObjectName("pastrecords")
        self.pastrecords.clicked.connect(self.openWindow)
        module3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(module3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1337, 26))
        self.menubar.setObjectName("menubar")
        module3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(module3)
        self.statusbar.setObjectName("statusbar")
        module3.setStatusBar(self.statusbar)

        self.retranslateUi(module3)
        QtCore.QMetaObject.connectSlotsByName(module3)

    def retranslateUi(self, module3):
        _translate = QtCore.QCoreApplication.translate
        module3.setWindowTitle(_translate("module3", "MainWindow"))
        self.label.setText(_translate("module3", "RequestFor"))
        self.label_2.setText(_translate("module3", "Pant"))
        self.label_3.setText(_translate("module3", "Shirt"))
        self.label_4.setText(_translate("module3", "Kurti"))
        self.label_5.setText(_translate("module3", "Punjabi"))
        self.label_6.setText(_translate("module3", "Price"))
        self.label_7.setText(_translate("module3", "Quantity"))
        self.m_bt.setText(_translate("module3", "OK"))
        self.label_8.setText(_translate("module3", "Address:"))
        self.label_9.setText(_translate("module3", "Rs.10"))
        self.label_10.setText(_translate("module3", "Rs.8"))
        self.label_11.setText(_translate("module3", "Rs.20"))
        self.label_12.setText(_translate("module3", "Rs.20"))
        self.qc_bt.setText(_translate("module3", "Any Queries Or Complaints"))
        self.label_15.setText(_translate("module3", "Total"))
        self.Calculate.setText(_translate("module3", "Calculate"))
        self.label_17.setText(_translate("module3", "Date and time"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("module3", "Morning"))
        item = self.listWidget.item(1)
        item.setText(_translate("module3", "After None"))
        item = self.listWidget.item(2)
        item.setText(_translate("module3", "Evening"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pastrecords.setText(_translate("module3", "Past Records"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    module3 = QtWidgets.QMainWindow()
    ui = Ui_module3()
    ui.setupUi(module3)
    module3.show()
    sys.exit(app.exec_())
